apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: postgres-db
spec:
  destination:
    name: ''
    namespace: myapp
    server: 'YOUR K8S CLUSTER URL'
  source:
    path: k8s-manifests/db
    repoURL: https://github.com/StoreMyProjects/flask-postgresql-app
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true