apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
  labels:
    app: two-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: two-tier-app
          image: amrendra01/exploreexpeditionsapp:latest
          env:
            - name: host
              value: "10.8.65.117"
            - name: dbname
              value: "exploreexpeditionsdb"
            - name: user
              value: "your_user"
            - name: password
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5000
          imagePullPolicy: Always