apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  labels:
    app: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: "exploreexpeditionsdb"
            - name: POSTGRES_USER
              value: "your_user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-initdb
              mountPath: docker-entrypoint-initdb.d
      volumes:
        - name: postgres-initdb
          configMap:
            name: psql-initdb-config    # Config name